### ISSUE TITLE
About resources

### ISSUE THREAD

**Issue by bangbangmihir** [bhatvikrant/bhatVikrant#3]
Best resources for learning react js.

**Comment by bhatvikrant** [comment]
Hey Mihir, 
One of the best place to learn React is the [React docs](https://reactjs.org)

After that there are a lot of free tutorials on youtube, which you can follow. I would recommend the following two channels:
1. [Codedamn](https://youtube.com/c/codedamn)
2. [Codevolution](https://youtube.com/c/Codevolution)

[Freecodecamp](https://freecodecamp.org) also has a free thorough curriculum for react, do check that out.

Hope this helps you 😇

**Comment by bangbangmihir** [comment]
Thanks..
